"""Build auditable UTF-8 source/claim registers from handoff and reviewed notes. No network."""
from pathlib import Path
import re,json,hashlib,collections
ROOT=Path(__file__).resolve().parents[1]
handoff=(ROOT/'HANDOFF_INPUT.md').read_text(encoding='utf-8')
sources={}
def add(sid,title,publisher,url,date=None,revision=None,period=None,kind='PRIMARY_DOCUMENT',depth='DISCOVERED',family=None,locator=None,limit=None,coi='기관·저자의 관점이며 연구자의 독립 검증을 뜻하지 않음',local=None,alts=None,research=False):
    d=dict(source_id=sid,title=title,authors_or_publisher=publisher,canonical_url=url,alternate_urls=alts or [],publication_date=date,revision_date=revision,accessed_at=None if depth=='DISCOVERED' else '2026-09-21 KST (session date; exact fetch time in local manifest when available)',observation_period=period,source_type=kind,read_depth=depth,source_family_id=family or sid,independence_note='같은 family의 판본·보도자료·대시보드는 독립 근거로 중복 계산하지 않음. 다른 family도 원데이터가 겹칠 수 있음.',relevant_claim_ids=[],exact_locator=locator,access_limit=limit,conflict_of_interest_note=coi,reviewed_research_family=research)
    d['unknown_metadata_reason']='null은 원문에서 이번 실행에 확인하지 못했거나 해당 없음; 발행일과 관측일을 추정하지 않음'
    if local:
        p=ROOT/'data/raw'/local
        if p.exists():
            d.update(local_path='data/raw/'+local,sha256=hashlib.sha256(p.read_bytes()).hexdigest(),data_version=revision or period or 'retrieved session snapshot')
    sources[sid]=d
for m in re.finditer(r'### (S\d+) · (.*?)\n(.*?)(?=\n### S|\n## 부록 B)',handoff,re.S):
    sid,title,body=m.groups(); pub=re.search(r'발행/작성: (.*)',body)[1];url=re.search(r'원문/입구: (https?://\S+)',body)[1]
    add(sid,title,pub,url,limit='초기 패킷의 접근 기록을 승계하지 않음. 이번 실행 본문 미검토; 관련 대체 원출처를 별도 등록.')
def upd(sid,**kw): sources[sid].update(kw)
for sid,depth,loc,fam in [
('S01','SUMMARY_READ','공식 페이지 요약: modern money as IOUs','BOE_MONEY2014'),
('S02','SECTIONS_READ','PDF money creation, loans/deposits, reserves/QE sections','BOE_MONEY2014'),
('S03','SECTIONS_READ','2025 edition: reserve composition, international usage figures and notes','FED_DOLLAR2025'),
('S07','METHODS_RESULTS_READ','June2026 PDF §§2–4; Eq.2; Table2 PDF p17; impulse responses and exclusion diagnostics','BIS1270'),
('S10','PORTAL_READ','reserve report links; dashboard values not extracted','CIRCLE_RESERVES'),
('S11','PORTAL_READ','reserve reports and June2026 report discovery','TETHER_RESERVES'),
('S12','SECTIONS_READ','Key Takeaways; interest-rate risk, deposit concentration, supervision','FED_SVB2023'),
('S13','FULL_SHORT_DOCUMENT_READ','2024-06-13 release on civil verdict and settlement','SEC_TERRAFORM2024'),
('S17','SECTIONS_READ','What is the oracle problem? correctness, availability, incentives','ETHEREUM_DOCS'),
('S18','SECTIONS_READ','overview §§2.3–2.4; Checkout Mandates; human-present/absent flows; card/x402 examples','AP2'),
('S20','METHODOLOGY_PARTIAL','Transactions page labels and linked methodology; no timeseries export','VISA_ALLIUM'),
('S21','METHODOLOGY_PARTIAL','Agentic Payments coverage and metric labels; no underlying transactions','VISA_ALLIUM'),
('S22','METHODOLOGY_PARTIAL','Stablecoin registry product_id/is_native; supply/transfer metric definitions','VISA_ALLIUM'),
('S23','METHODS_RESULTS_READ','arXiv v2 abstract; deployment/design/results/robustness sections; QJE final metadata','GENAI_WORK'),
('S24','METHODS_RESULTS_READ','May2024 PDF §3.2–3.3, PDF pp30–34; assumptions and conclusion','ACEMOGLU_AI'),
('S25','METHODS_RESULTS_READ','PDF §§2–3, D.1; randomized task assignment, adjusted/raw effects, limitations','METR_PRODUCTIVITY'),
('S26','EXECUTIVE_SUMMARY_READ','2025 executive summary; 2024 estimates vs2030 scenario','IEA_AI_ENERGY'),
('S27','SECTIONS_READ','2026-07-17 text/appendix on measurement, investment/imports, productivity indicators','FED_AI_BUILDOUT')]:
    upd(sid,read_depth=depth,accessed_at='2026-09-21 KST',exact_locator=loc,source_family_id=fam,access_limit='전체 문헌 또는 데이터 전체 정독·재현을 뜻하지 않음')
for sid,local,period,rev in [('S02','boe_creation.pdf','modern UK banking','2014'),('S07','bis1270_june2026.pdf','2021-01 to 2026-03','2026-06'),('S23','generative_ai_work_v2.pdf','firm-specific staggered deployment; 5,172 agents','2024-11-06 arXiv v2'),('S24','acemoglu_may2024.pdf','conditional next 10 years from model baseline','2024-05'),('S25','metr2025.pdf','2025-02 to 2025-06 tools/tasks','2025-07-10')]:
    p=ROOT/'data/raw'/local;upd(sid,local_path='data/raw/'+local,sha256=hashlib.sha256(p.read_bytes()).hexdigest(),data_version=rev,revision_date=rev,observation_period=period)
for sid in ['S07','S23','S24','S25']:upd(sid,reviewed_research_family=True,source_type='RESEARCH_PAPER')
upd('S03',publication_date='2025-07-18',observation_period='reserve shares through2024; other series vary; no 2026 edition verified')
upd('S18',alternate_urls=['https://ap2-protocol.org/overview/','https://github.com/google-agentic-commerce/AP2'],revision_date='moving website; repository main SHA e1ea56db72a6385bce3e5c1112b3a56ce60acb43 observed separately',access_limit='Repository SHA metadata saved; website contents not proven to match that commit. /specification returned404. No conformance test.')
add('S29','USDC June2026 reserve examination','Circle / independent accountant', 'https://6778953.fs1.hubspotusercontent-na1.net/hubfs/6778953/USDCAttestationReports/2026/2026%20USDC_Examination%20Report%20June%2026.pdf','2026-07-29',period='2026-06-02 and2026-06-30; analysis uses June30',kind='RESERVE_EXAMINATION',depth='SECTIONS_AND_TABLE_VISUAL_READ',family='CIRCLE_RESERVES',locator='PDF pp1–5; table p4, notes p5; rendered table/notes inspected',limit='Point-in-time reserve assertion; not full issuer financial audit, not continuous solvency.',coi='Management assertion with external reasonable assurance under AICPA; issuer commissions report.',local='circle_june2026.pdf')
add('S30','Consolidated Financial Figures and Reserves Report June2026','Tether / BDO', 'https://assets.ctfassets.net/vyse88cgwfbl/2kYf7r64h3tzwiu6F0CbUB/2997abd2f11ecea74a21528048b50707/Opinion___Report_-_Tether_International_Financial_Figure_30-06-2026.pdf','2026-07-31',period='2026-06-30',kind='RESERVE_ASSURANCE',depth='SECTIONS_AND_TABLE_VISUAL_READ',family='TETHER_RESERVES',locator='PDF p9 assets/liabilities, pp10–11 notes; assurance pp1–5; table p9 visually inspected',limit='ISAE3000R reasonable assurance of stated CFFRR; not complete issuer financial audit. Term repo collateral not identified as entirely US Treasuries.',coi='Issuer assertion, commissioned external assurance; press headline and token liabilities differ.',local='tether_june2026.pdf')
add('S31','Circle Q2 2026 results, 8-K Exhibit99.1','Circle / SEC filing', 'https://www.sec.gov/Archives/edgar/data/1876042/000187604226000246/augustepr-circle_q22026f.htm','2026-08-05',period='three months ended2026-06-30',kind='UNAUDITED_FINANCIAL_RELEASE',depth='FINANCIAL_TABLE_READ',family='CIRCLE_FINANCIALS',locator='Consolidated statements of operations; accession0001876042-26-000246; reserve income/distribution/opex/continuing net income',limit='Web full tables accessible; direct urllib download403. CPN/x402 adoption claims issuer-reported, not independently verified.',coi='Issuer prepared financial release; SEC hosting is not SEC endorsement.',alts=['https://www.circle.com/pressroom/circle-reports-second-quarter-2026-results'])
add('S32','Treasury Buyback FAQs','TreasuryDirect','https://www.treasurydirect.gov/help-center/faqs/buyback-faqs/',period='current FAQ retrieved2026-09-21',kind='OFFICIAL_POLICY_EXPLANATION',depth='SECTIONS_READ',family='TREASURY_BUYBACK',locator='purposes, financing, authority31USC3111/31CFR375',limit='Not executed operations dataset.')
add('S33','Treasury Announces Update to Treasury Buyback Program','U.S. Treasury','https://home.treasury.gov/news/press-releases/sb0607','2026-08-19',period='planned operations2026-09-09 to2026-11-04',depth='FULL_SHORT_DOCUMENT_READ',family='TREASURY_BUYBACK',locator='10–20y and20–30y nominal sectors maximum purchase sizes',limit='Announcement/maximums, not actual realized volume.')
add('S34','Public Debt and Low Interest Rates','Olivier Blanchard','https://www.piie.com/sites/default/files/documents/wp19-4.pdf','2019',period='historical US rates plus theoretical OLG calibration',kind='RESEARCH_PAPER',depth='METHODS_RESULTS_READ',family='BLANCHARD_DEBT2019',locator='introduction, model/welfare distinctions, rollover risk/counterarguments; AER109(4),1197–1229',limit='No current US debt forecast or unconditional free debt claim.',local='blanchard2019.pdf',alts=['https://doi.org/10.1257/aer.109.4.1197'],research=True)
add('S35','Budget and Economic Outlook 2026 to2036','CBO','https://www.cbo.gov/publication/61882','2026-02',period='2026–2036 projection',kind='OFFICIAL_PROJECTION',depth='SEARCH_SUMMARY_ONLY',family='CBO2026',locator='search excerpt headline public debt101% to120%; not adopted as calibrated model input',limit='Complete tables/methods not read; followup publication62105 and govinfo copy discovered.',alts=['https://www.cbo.gov/publication/62105','https://www.govinfo.gov/content/pkg/CMR-Y10-00199317/pdf/CMR-Y10-00199317.pdf'])
add('S36','Banks in the Age of Stablecoins','Jessie Jiaxu Wang / Federal Reserve','https://www.federalreserve.gov/econres/notes/feds-notes/banks-in-the-age-of-stablecoins-implications-for-deposits-credit-and-financial-intermediation-20251217.html','2025-12-17',period='conceptual balance-sheet pathways',depth='SECTIONS_READ',family='FED_BANK_STABLECOIN',locator='deposit reduction, recycling/restructuring channels and reserve allocation',limit='Mechanism analysis; no estimated population net effect.')
add('S37','Stablecoin Shocks, WP26/44','Eugenio Cerutti, Melih Firat, Martina Hengge, Takaaki Sagawa / IMF','https://www.imf.org/-/media/files/publications/wp/2026/english/wpiea2026044-source-pdf.pdf','2026-03-06',period='2019-01-01 to2025-06-30',kind='RESEARCH_PAPER',depth='METHODS_RESULTS_READ',family='IMF_STABLECOIN_SHOCKS',locator='§2.2 heteroskedasticity/event identification; §3.1/Table1 PDFp14; dynamic SVAR',limit='Web PDF read; local download403. CoinGecko/Bloomberg inputs not reconstructed; identification assumptions conditional.',alts=['https://www.imf.org/en/publications/wp/issues/2026/03/06/stablecoin-shocks-574528'],research=True)
add('S38','GENIUS Act, Public Law119–27','U.S. Congress / GovInfo','https://www.govinfo.gov/content/pkg/PLAW-119publ27/pdf/PLAW-119publ27.pdf','2025-07-18',period='enacted statute; implementation separately checked',kind='STATUTE',depth='SECTIONS_READ',family='US_GENIUS',locator='§4 issuer/reserve requirements; §20 effective date PDFp48',limit='Enacted is not evidence every rule is effective; no individual legal advice.',local='genius_act.pdf')
add('S39','OCC GENIUS rule proposal and subsequent implementation remarks','OCC','https://www.occ.gov/news-issuances/news-releases/2026/nr-occ-2026-69.html','2026-08-19',period='Feb25 proposal; Aug19 plan for final rule byNovember',kind='RULEMAKING_STATUS',depth='SECTIONS_READ',family='US_GENIUS',locator='implementation schedule remarks; Feb25proposal',limit='Final rule completion not verified asofretrieval; search non-discovery is not proof of absence.',alts=['https://www.occ.gov/news-issuances/news-releases/2026/nr-occ-2026-9.html'])
add('S40','Markets in Crypto-assets Regulation2023/1114','European Union','https://eur-lex.europa.eu/eli/reg/2023/1114/oj/eng','2023-05-31',period='TitlesIII/IV apply2024-06-30; general2024-12-30',kind='REGULATION',depth='SECTIONS_READ',family='EU_MICA',locator='Arts48–50 EMT authorisation/claim/par redemption/no interest; Art149 application dates',limit='Read original regulation; not exhaustive delegated rules or entity-specific licensing review.')
add('S41','HKMA Annual Report2025: International Financial Centre','HKMA','https://www.hkma.gov.hk/media/eng/publication-and-research/annual-report/2025/16_International_Financial_Centre.pdf',period='2025 annual report with2026 licensing update',kind='REGULATOR_REPORT',depth='SEARCH_EXCERPT_ONLY',family='HKMA_STABLECOIN',locator='licensing regime commencement and first licences excerpt',limit='Full PDF access unsuccessful; legal text and current license register not checked; not used to certify current licensees.')
add('S42','Update on AI developer productivity measurement','METR','https://metr.org/blog/2026-02-24-uplift-update/','2026-02-24',period='later2025; original10 and new47 developers,800+tasks',kind='RESEARCH_UPDATE',depth='METHODS_RESULTS_READ',family='METR_PRODUCTIVITY',locator='original/new subsamples, uncertainty intervals, selection/pay/concurrency caveats',limit='Same research family asS25; authors warn estimates unreliable for current aggregate effect.')
add('S43','The Effects of Generative AI on High-Skilled Work: Evidence from Three Field Experiments','Cui et al.','https://economics.mit.edu/sites/default/files/inline-files/draft_copilot_experiments.pdf',revision='2025-02 author draft; SSRN2025-08-21 metadata,2026journal metadata',period='three company experiments,2022–2024;4,867developers',kind='RESEARCH_PAPER',depth='METHODS_RESULTS_READ',family='CUI_COPILOT',locator='experimental designs, imperfect compliance/IV, preferred pooled estimate and tables',limit='26.08% is IV estimate for tool use, not generic ITT. Final2026publisher body not reconciled.',coi='Includes participating tech firms/Microsoft research; independent fromMETR design but shared tools/context.',local='cui2025.pdf',alts=['https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4945566'],research=True)
add('S44','Firm Data on AI, NBER34836','Yotzov et al.','https://www.nber.org/papers/w34836','2026-02',period='four-country executive survey',kind='RESEARCH_PAPER',depth='ABSTRACT_ONLY',family='FIRM_AI2026',locator='search-indexed abstract only',limit='Landing403; full paper and questionnaire not read. Self-reports and expectations not measured causal productivity.',alts=['https://www.nber.org/system/files/working_papers/w34836/w34836.pdf'])
add('S45','Key Questions on Energy and AI','IEA','https://www.iea.org/reports/key-questions-on-energy-and-ai/executive-summary','2026-04-16',period='2025 estimates and forward scenarios',kind='INSTITUTIONAL_ESTIMATES',depth='EXECUTIVE_SUMMARY_READ',family='IEA_AI_ENERGY',locator='electricity demand, efficiency/rebound, investment and bottlenecks summary',limit='All data centres not equivalent toAI; estimates vsforecasts distinct; methodology appendix not fully read.',alts=['https://www.iea.org/reports/key-questions-on-energy-and-ai'])
add('S46','Microsoft FY2026 Q4 results','Microsoft','https://www.microsoft.com/en-us/investor/earnings/fy-2026-q4/press-release-webcast',period='FY2025 andFY2026 endedJune30',kind='UNAUDITED_FINANCIAL_RELEASE',depth='FINANCIAL_TABLE_READ',family='MSFT_FINANCIALS',locator='income statement, balance sheet, cash flows; fiscal year columns',limit='IR financial tables unaudited label; SEC10K too large for complete read. Whole company, no isolatedAI cashflow; cash capex excludes noncashlease additions.',coi='Issuer financial disclosure; not independent evidence ofAI returns.',alts=['https://www.sec.gov/Archives/edgar/data/789019/000119312526323660/msft-20260630.htm'])
add('S47','Bank of Amsterdam historical work: monetary competition / shadow banking crisis','Quinn and Roberds / Federal Reserve Bank of Atlanta','https://fedinprint.org/item/fedawp/13430/original','2012',period='historical Amsterdam',kind='HISTORICAL_RESEARCH_CANDIDATE',depth='ABSTRACT_ONLY',family='QUINN_ROBERDS',locator='Fed repository metadata/abstract; referenced byS48',limit='Original Atlanta paths failed; EconStor challenge. Two related titles discovered, no full-body conclusions adopted.')
add('S48','The Bank of Amsterdam and the limits of fiat money, BIS1065','Bolt, Frost, Shin, Wierts','https://www.bis.org/publications/working-paper-1065-bank-amsterdam-and-limits-fiat-money.pdf','2023',revision='2023-11',period='Amsterdam1609–1820; global-games model',kind='HISTORICAL_RESEARCH',depth='METHODS_RESULTS_READ',family='BIS_AMSTERDAM',locator='§II historical mechanisms PDFpp7–10; model setup; fiscal backing/conclusion PDFpp26–28',limit='Archival research synthesized by authors; original city records not inspected; fiat/stablecoin analogies not institutional identity.',local='bis1065_nov2023.pdf',research=True)
add('S49','Cuneiform tablet: loan of silver','Metropolitan Museum of Art','https://www.metmuseum.org/art/collection/search/321802',period='Babylonia ca1646BCE',kind='OBJECT_CATALOG',depth='CATALOG_READ',family='MET_SILVER_TABLET',locator='object86.11.224 date/material/classification',limit='Museum primary object catalog; original tablet not translated independently; cannot establish universal monetary origins.')
add('S50','Project Han River research release','Bank of Korea','https://www.bok.or.kr/portal/bbs/B0000502/view.do?menuNo=201265&nttId=11062536','2026-07-01',period='deposit-token pilot/research',kind='PILOT_RESEARCH_PORTAL',depth='PORTAL_READ',family='BOK_HANRIVER',locator='press/paper/Korean summary attachment listing; nttId11062536',limit='Attachment retrieval failed; cannot infer commercial scale or counterfactual efficiency from title.')
add('S51','Bitcoin Core supply validation code','Bitcoin Core contributors','https://raw.githubusercontent.com/bitcoin/bitcoin/v30.0/src/validation.cpp',revision='v30.0 pinned; not claimed latest release',period='consensus rule at pinned version',kind='PROTOCOL_CODE',depth='CODE_SECTIONS_READ',family='BITCOIN_CORE',locator='GetBlockSubsidy lines1922–1931; block subsidy/fees check; mainnet subsidy interval in chainparams.cpp',limit='No full node run or complete latest-version audit; supply rule is not return evidence.',local='bitcoin_validation.cpp',alts=['https://raw.githubusercontent.com/bitcoin/bitcoin/v30.0/src/kernel/chainparams.cpp'])
add('S52','EIP1559: Fee market change','Ethereum EIP authors','https://eips.ethereum.org/EIPS/eip-1559',period='EIP specification; implementation history',kind='PROTOCOL_SPECIFICATION',depth='SPEC_SECTIONS_READ',family='ETHEREUM_FEES',locator='Specification: base fee burn and priority fee',limit='Not full2026network economic dataset or complete currentfork audit.',local='eip1559.html')
add('S53','EIP4844: Shard Blob Transactions','Ethereum EIP authors','https://eips.ethereum.org/EIPS/eip-4844',period='blob fee design',kind='PROTOCOL_SPECIFICATION',depth='SPEC_SECTIONS_READ',family='ETHEREUM_FEES',locator='blob gas accounting and fee market',limit='Later parameter changes not exhaustively audited; nocurrentfee/MEVmeasurement.',local='eip4844.html')
add('S54','Risks and Returns of Cryptocurrency','Liu and Tsyvinski','https://www.nber.org/papers/w24877','2018',revision='RFS2021 final metadata',period='early cryptocurrency sample; dates not verified',kind='RESEARCH_PAPER',depth='ABSTRACT_ONLY',family='LIU_TSYVINSKI',locator='primaryabstract, Yale author bibliography',limit='NBERPDF403/publisher failure; fullmethods notread; historicalabstract not universal hedge evidence.',alts=['https://economics.yale.edu/people/aleh-tsyvinski/papers'])
add('S55','USDe underlying derivatives','Ethena','https://docs.ethena.fi/protocol-overview/underlying-derivatives',period='moving documentation retrieved2026-09-21',kind='ISSUER_PROTOCOL_DOCUMENTATION',depth='FULL_SHORT_DOCUMENT_READ',family='ETHENA',locator='Context and Overview: spot backing plus short futures/perpetuals, mint/redemption hedging',limit='Oldoverview404; markdownalternative failed; validpage read. No live positions/reserves/funding stress replication.',coi='Issuer describes its own risk design; delta neutrality is an objective, not solvency guarantee.')
add('S56','x402 documentation','x402 / Coinbase ecosystem','https://docs.x402.org/introduction',period='moving docs; main SHA dd927a26cfefc98c24b3ec38b3a8f204dad0c60d separately observed',kind='PROTOCOL_DOCUMENTATION',depth='SECTIONS_READ',family='X402',locator='introduction, exact/upto scheme links, settlement/idempotency/signedoffers navigation',limit='No payment, signature or conformance run; repository metadata saved but not executed. Homepage countersnotverifiedcommercialreceipts.',alts=['https://x402.org/','https://github.com/coinbase/x402'])
add('S57','Sky collateral liquidation and LitePSM','Sky ecosystem','https://developers.skyeco.com/protocol/vaults/collateral-liquidation/',period='moving docs retrieved2026-09-21',kind='PROTOCOL_DOCUMENTATION',depth='SECTIONS_READ',family='SKY',locator='auction parameters/keeper incentives/oracle use; LitePSM overview and deployment notes',limit='No live collateral inventory/solvency claim; USDC-linked PSM means not purely crypto collateral.',coi='Protocol developer documentation.',alts=['https://developers.skyeco.com/protocol/liquidity/litepsm/'])
datasets=[('CBBTCUSD','Coinbase viaFRED','USD perBTC; daily; crypto closing time differs fromequity'),('SP500','S&P Dow Jones Indices viaFRED','price index, dividends excluded; daily'),('NASDAQCOM','Nasdaq viaFRED','price index; daily'),('CPIAUCSL','BLS viaFRED','monthly SA1982–84=100; October2025 missing in snapshot'),('DEXKOUS','Federal Reserve H10 viaFRED','KRW perUSD; businessdaily; US noon quote'),('DTWEXBGS','Federal Reserve H10 viaFRED','broad trade-weighted dollarindex; daily'),('DGS3MO','Federal Reserve H15 viaFRED','3m constantmaturity investmentbasis annualizedpercent; notbilltotalreturn'),('DGS10','Federal Reserve H15 viaFRED','10y constantmaturity percent; nottotalreturn'),('DFF','Federal Reserve H15 viaFRED','effective federalfundsratepercent; daily'),('KORCPIALLMINMEI','OECD viaFRED','monthly NSA2015=100; ends2023-11 in acquiredseries')]
manifest=json.loads((ROOT/'data/raw/DOWNLOAD_MANIFEST.json').read_text())
byfile={x['filename']:x for x in manifest}
for i,(series,pub,unit) in enumerate(datasets,1):
    sid=f'D{i:02}';name=f'fred_{series}.csv'
    add(sid,series,pub,'https://fred.stlouisfed.org/series/'+series,period='requested2015-01-01 to2026-09-18; actualvalidrange indata_inventory.csv',kind='TIME_SERIES',depth='DATA_ANALYZED',family='FRED_'+('FED_H15' if series in ['DGS3MO','DGS10','DFF'] else series),locator=unit,limit='Current vintage, not point-in-time vintage. No perobservation release timestamp archive.',local=name,alts=[byfile[name]['requested_url']])
    upd(sid,accessed_at=byfile[name]['accessed_at'],data_version='download SHA256; valid dates/counts in data/derived/data_inventory.csv')
add('X01','Gold benchmark data access attempts','FRED / Stooq','https://fred.stlouisfed.org/series/GOLDAMGBD228NLBM',period='intended2015–2026',kind='DATA_CANDIDATE',depth='ACCESS_LIMITED',family='GOLD_DATA_ATTEMPTS',locator='DOWNLOAD_MANIFEST entries fred_GOLDAMGBD228NLBM.csv and gold_gld_stooq.csv',limit='FRED404; Stooq HTTP200 HTMLchallenge, not CSV; no gold return comparison.',alts=['https://stooq.com/q/d/l/?s=gld.us&i=d&d1=20160101&d2=20260918'])

# Explicit mapping to original questions; assessments refer to refined statements.
initial=dict(re.findall(r'\| (H\d{2}) \| (.*?) \|',handoff))
claims=[]
def claim(n,text,typ,scope,mechanism,support,challenge,alternatives,tests,assessment,uncertainty,falsify,change):
    sid=f'H{n:02}'
    d=dict(claim_id=sid,initial_statement=initial[sid],refined_statement=text,claim_type=typ,scope_and_horizon=scope,mechanism=mechanism,supporting_source_ids=support.split(),challenging_source_ids=challenge.split(),alternative_explanations=alternatives,data_or_test_ids=tests.split(),assessment=assessment,uncertainty=uncertainty,falsification_condition=falsify,decision_delta=change)
    claims.append(d)
claim(1,'수용은 희소성 하나보다 청구권·결제 제도·네트워크·재정 기반의 조합에 의존한다.','제도/역사','현대 은행 및Amsterdam사례','부채결제와 상환가능성, 수용네트워크','S01 S02 S48 S49','S51','희소자산은 법적 청구권 없이도 거래 가능','T01','CONDITIONAL','세금의 필수성·보편적 기원은 식별 안 됨','법적·네트워크 조건 없이 동일 수용성이 지속되는 비교증거','REFINED')
claim(2,'화폐의 단일 발전단계 설명은 보류하고 신용·금속·계정화폐 병존을 채택한다.','역사','고대 은대출 기록;17–18세기Amsterdam','금속소유권·예금·교환권의 병존','S48 S49','','고대 기록의 존재는 물물교환의 부재를 증명하지 않음','','SUPPORTED_IN_SCOPE','비서구 다지역 역사 정독 부족','다지역 사료가 단일 선형단계의 보편성을 지지','REFINED')
claim(3,'계산단위·지급수단·결제자산을 분리하면 접근성은 늘지만 상환·환전·유동성 마찰이 생긴다.','회계/제도','은행·토큰·거래상대방','예금/토큰 청구권을 최종결제 준비금과 구분','S02 S36 S40 S18','','완전 네팅과 동일은행 내이체는 자금이동을 줄임','T01 T05','SUPPORTED_IN_SCOPE','실제 거래별 총마찰 미측정','실제 비용자료에서 분리구조의 추가마찰이 소멸','RETAINED_IN_SCOPE')
claim(4,'신뢰는 발행·수탁·검증·외부정보·법적 집행으로 분해되며 완전히 제거되지 않는다.','제도/규칙','검토한 결제·오라클 구조','검증가능한 코드와 외부사실 보증 분리','S17 S18 S29 S30 S55 S57','','통제권 분산이 특정 단일장애를 줄일 수 있음','','SUPPORTED_IN_SCOPE','실제 지분/키/업그레이드권 집중도 미계량','외부 의존 없이 동일 청구권·실물계약 집행을 입증','RETAINED_IN_SCOPE')
claim(5,'달러 구매력·환율·국제사용은 별도 지표이며 방향이 다를 수 있다.','실증/측정','2022수익률;2024준비통화자료','국내물가와 상대환율·네트워크수요 분리','S03 D04 D05 D06','S37','금리차·안전자산선호가 구매력하락과 달러강세를 동반','T04','SUPPORTED_IN_SCOPE','2026국제사용 전체분포 미확보','동일시점 동일정의 자료에서 분리를 반박','RETAINED_IN_SCOPE')
claim(6,'부채비율은 평균금리·성장·기초적자·조정·차환속도의 조건부 결과다.','회계/모형','가상10년;미국예측 아님','b_t=(1+i)/(1+g)b_prev+d+sfa','S34','','낮은 r-g라도 지속적 적자·위험프리미엄 상승 가능','T02','CONDITIONAL','i,g,d의 내생성·불확실성 미추정','금리/성장/적자 경로 변화로 결과역전','RETAINED_IN_SCOPE')
claim(7,'재무부 바이백과QE는 자금원천·중앙은행 자산 변화가 달라 동일하지 않다.','회계/제도','통합은행 가상거래;현행FAQ','TGA인출은연준부채재배치;QE는자산/준비금확대','S02 S32 S33','','시점차·RRP자금조달이면 단기준비금경로가 다름','T01','SUPPORTED_IN_SCOPE','ONRRP/레포/발행만기 실제시계열 분해 미수행','자금원천과 거래상대방이 달라질 때 원장 재작성','REFINED')
claim(8,'스테이블코인 충격의 단기국채 금리효과는 조건부 지지되나 장기·위험자산 필연적 전파는 미확인이다.','인과','BIS2021–26;IMF2019–25','단기 안전자산 수요와 한계가격','S07 S37','','공통 위험선호·정책기대·국채공급·직접 규제뉴스효과','T03','CONDITIONAL','IV/이분산 식별가정;동일 데이터 일부 중복','별도 식별충격/통제에서 효과 소멸·부호역전','REFINED')
claim(9,'디지털 달러 접근 확대와 기존 달러상품 대체는 함께 가능하다.','인과/제도','관측사용자 전체는 미식별','접근비용 하락과 자산포트폴리오 재배치','S36 S18 S40','S20 S22','크립토거래·담보·저축 수요가 결제수요를 대체','T01','CONDITIONAL','지역별 신규사용자 원천자금자료 없음','동일 사용자 이전자산/실물결제 자료로 순확장 확인','REFINED')
claim(10,'발행사 국채노출은 계산 가능하나 글로벌 순증 국채수요의 크기는 식별하지 못했다.','인과','June2026보유잔액;가상증분','발행사증가분에서 대체된 기존국채노출 차감','S29 S30 S36','S07 S37','MMF/직접국채 대체 또는 은행 자산조정','T01 T03','INSUFFICIENT_EVIDENCE','자금원천·매도자 포트폴리오·상환자료 없음','투자자연결 자금흐름/반사실자료로 순증 추정','HELD')
claim(11,'발행은 예금 소유자/자산구성 변화를 만들며 준비금이나 통화량의 자동 순증이 아니다.','회계','가상통합은행원장','은행간 준비금 이동과 전체규모 분리','S02 S36','','통계상 money-holder범위·해외/비은행 분류에 따라통화량변화','T01','SUPPORTED_IN_SCOPE','실제 금융중개 반응은 모형 밖','새은행대출/중앙은행거래를 포함할 때 별도경로 발생','REFINED')
claim(12,'결제액 증가가 회전속도 증가로 상쇄되면 결제 목적 잔액은 늘지 않는다.','모형/회계','동일기간단위 가상흐름','B≈P/v;저축·담보 추가','S20 S22','','대기자금·담보·저축이 잔액증가 주도 가능','T07','SUPPORTED_IN_SCOPE','관측된 결제액/잔액 정의가 불일치','동일 고객군에서v고정과P증가로B증가 확인','REFINED')
claim(13,'준비자산 품질과 상환 접근권·수탁·유동성은 각각 페그에 기여한다.','제도/인과','공시시점·US/EU 규칙','자산가치충분조건과 현금화접근조건 분리','S29 S30 S38 S40','S12','건전자산도 운영중단/상환제한이면 할인 가능','T03','CONDITIONAL','소매고객별 직접상환 조건·실제 지연 미조사','실제stress에서도 모든계층의신속상환이 확인','REFINED')
claim(14,'은행·알고리즘·거래소/브리지·합성형 실패를 동일 담보문제로 묶을 수 없다.','제도/사례','SVB2023;Terra2024발표;현재 문서','만기위험·반사적발행·수탁/코드·파생헤지 위험 분리','S12 S13 S17 S55 S57','','공통요인은유동성경색·상환접근·동시매도','','SUPPORTED_IN_SCOPE','Terra세부경제데이터/브리지사고원문미검토','사례별손실분해가동일원인으로수렴','REFINED')
claim(15,'은행토큰·카드·계좌·스테이블코인은 대체·보완 관계가 가능하다.','제도/시나리오','AP2문서와공개파일럿','권한프로토콜과결제자산 선택 분리','S18 S36 S50','','은행영업시간·국경접근·법적권리가 용도별 선택 결정','T05','CONDITIONAL','동일 고객/업무 상용비교 데이터 부족','반복 상업거래에서 대체망이 지속 불가능함을 입증','RETAINED_IN_SCOPE')
claim(16,'법적 청구권과 시행 상태는 관할별로 다르며 US법성립과 규칙시행을 분리해야 한다.','제도/규칙','2026-09-21열람시점 US/EU중심','허용자산·상환권·발행인가·시행일','S38 S39 S40','S41','같은달러표시라도발행관할/이용자지위가 다름','','SUPPORTED_IN_SCOPE','US최종시행규칙 전수미확인;HK/KR법률검토제한','공식finalrule와발효통지가새로확인되면업데이트','REFINED')
claim(17,'고정 공급규칙은 확인되나 안정적 인플레이션·위기 헤지 주장은 관측 반례가 있다.','규칙/실증','v30.0코드;2017–2025월별,2026별도','공급제약과수요/위험프리미엄 변동 분리','S51 D01 D02 D04 D05 D10','S54','장기상승·일부저상관구간은 분산효과와양립','T04','MIXED','금미확보;예상밖물가 미분리;관측연구','사전지정 표본에서 인플레충격/위기손실 완충이 반복확인','REFINED')
claim(18,'비트코인 프리미엄의 보안·접근·수탁·유동성별 인과 기여도는 보류한다.','인과','검토자료 범위','수요·보안예산·유통제약의 상호작용','S51','D01 S54','거시위험선호·투기·접근성 개선이 동시변화','T04','INSUFFICIENT_EVIDENCE','채굴비·수탁흐름·시장깊이 패널 미확보','독립 충격으로각기여분이식별','HELD')
claim(19,'수수료·소각·검증자보상·L2마진은 다른 귀속이며 토큰보유자의 배당이 아니다.','규칙/경제해석','EIP1559/4844 설계','기본료소각·우선료·별도blob가격','S52 S53','','경쟁·발행량·MEV·실행위치가 토큰가치연결 바꿈','T08','SUPPORTED_IN_SCOPE','최신 모든fork/MEV/L2수익시계열 미검토','직접현금청구권 또는강한순수요연결이별도 입증','REFINED')
claim(20,'사용량 성장과 특정 체인/토큰 가치 귀속은 분리될 수 있다.','모형/시나리오','L1/L2/기존 결제 경쟁','단가하락·결제자산선택·다른계층마진','S52 S53 S18','','보안/담보수요가 별도 토큰수요를 만들 수도 있음','T07 T08','CONDITIONAL','플랫폼별장기탄력성/임대료 미계량','수량증가보다가격과마진효과가일관되게작음','REFINED')
claim(21,'에이전트 지급은 명시적 위임과 검증 가능한 증거·한도를 필요로 한다.','제도/규칙','현재 AP2/x402문서;오프라인모형','서명mandate·예산·만료·재시도중복방지','S18 S56','','책임/환불은네트워크계약과법에의존','T05','SUPPORTED_IN_SCOPE','mock은서명/실결제/환불검증아님','동일한통제없는지급이동등한책임보호를입증','RETAINED_IN_SCOPE')
claim(22,'AP2는 카드 등 복수수단을 지원하며 에이전트 일반에 퍼블릭체인이 필수라는 근거는 없다.','규칙/시나리오','검토한프로토콜 적용범위','권한·서비스협상·결제레일 분리','S18 S56','','개방형미터링/국경간소액은토큰에유리할수있음','T05','SUPPORTED_IN_SCOPE','특정용도의필요성은고객별검증필요','동일업무에허용가능한비체인대안이없음이입증','REFINED')
claim(23,'반복 고객·환불차감 순매출을 입증하는 독립적 에이전트 결제 통계는 확보하지 못했다.','실증','검토대시보드/기업2026Q2발표','요청→성공지급→실물서비스→반복독립고객 분리','S20 S21 S22 S31 S56','','봇/인센티브/자기이전/집계주소가 활성도 부풀릴수있음','T05','INSUFFICIENT_EVIDENCE','통계부재는상용거래0을뜻하지않음','익명화영수증·독립고객코호트·순매출대조확보','HELD')
claim(24,'같은업무의총비용우위는 묶음정산·예치·램프·실패/사기비용에 달린다.','모형','1000건×0.01USD 가상API','고정비/배치수·변동비·기회비용','S18 S56','','월단위카드청구가건별가스보다쌀수있음','T05','CONDITIONAL','실제견적·FX·손실률 없음;승자선정불가','실측동일업무비용이모든조건에서일관된우위','REFINED')
claim(25,'AI 생산성 효과는 직무·숙련·도구·선택/측정에 따라 이질적이다.','인과/실증','S23v2,S25early2025,S43Febdraft,S42followup','보완효과와검토/맥락비용','S23 S43','S25 S42 S44','도구세대변화·채택선택·평행작업시간측정','T06','MIXED','서로다른모집단;원미시데이터미재현','동일과업/도구/품질통제의재현에서이질성축소','REFINED')
claim(26,'효율 개선 후 총연산/전력 반등은 가격전가·수요탄력성·에너지효율에 조건부다.','모형','가상고정품질탄력성분석','작업수×작업당연산×연산당전력','S26 S45','','공급상한·수요포화·품질상승으로단순탄력성불안정','T07','CONDITIONAL','실제수요탄력성미식별','효율충격후품질보정수요/전력의실측반응','REFINED')
claim(27,'설비투자·전력증가는실제자원수요증거이나 AI순생산성이나자본수익을직접입증하지않는다.','실증/측정','IEA2025추정;MSFTFY2026전체회사','투자·가동·감가·서비스매출의시차','S27 S45 S46','','예비설비·수입장비·과잉투자·비AI수요','T08','SUPPORTED_IN_SCOPE','AI전용가동률/수익/유지투자 분해불가','AI분리현금흐름과품질보정산출이동시에관측','REFINED')
claim(28,'AI의부채부담완화는 실질생산성→명목성장/세수·금리·분배 경로가 모두 조건부다.','모형/인과','AcemogluMay2024가정;가상부채10년','가격하락·세원·임금/이익·차환시차','S24 S27 S34','','실질성장상승에도디스인플레/금리상승/적자확대로효과상쇄','T02 T06 T07','CONDITIONAL','AI→세수→국채경로 직접인과추정 없음','명목성장/세수/금리 연결이 장기패널에서 식별','REFINED')
claim(29,'채택이익은이용자·유통·발행·기업·토큰에다르게귀속되고단계별누수가크다.','회계/실증','CircleQ2;MSFTFY;Ethereum규칙','매출−유통−운영비−투자/손실','S31 S46 S52 S53','','경쟁가격하락은소비자잉여로귀속가능','T08','SUPPORTED_IN_SCOPE','개별결제파트너계약/AI앱마진 미확보','권리와실제배분자료가직접비례귀속입증','REFINED')
claim(30,'잔액/이용성장이금리/단가하락·투자비에상쇄될수있다.','모형/실증','CircleQ2;MSFTFY2025/26;가상금리','수량×단가−비용과회계상감가/현금투자구분','S31 S46 S52 S53','','유통조건/규모경제 개선이상쇄효과를줄임','T08','SUPPORTED_IN_SCOPE','전체회사수치로AI단독실패판단금지','단가안정·단위비용하락·현금전환동반확인','RETAINED_IN_SCOPE')
claim(31,'디지털달러·은행토큰·공개체인·국소상용화·생산성/마진압박은병존가능한대안이다.','시나리오','중기조건부경로,확률미부여','규제·접근·회전율·정산선택·경쟁','S18 S36 S45 S46','','한경로성장이타경로완전소멸을요구하지않음','T08','CONDITIONAL','시장점유율·가격확률예측안함','REPORT시나리오별반증지표에따라축소/확대','REFINED')
claim(32,'후속관측은시점·정의·공개지연·개정빈티지와함께 연결별로설계해야한다.','측정/연구설계','후속연구우선순위','재고/흐름·사건/발표·관측/인과분리','S22 S27 D01 D04 D10','','비교가능성확보전합성점수는오류확대','T01 T02 T03 T04 T05 T06 T07 T08','SUPPORTED_IN_SCOPE','일부발표일빈티지없음;즉시매매입력으로승격불가','관측표가연결별실측오류를설명못하면수정','RETAINED_IN_SCOPE')
for c in claims:
    for sid in set(c['supporting_source_ids']+c['challenging_source_ids']):
        assert sid in sources,(c['claim_id'],sid)
        sources[sid]['relevant_claim_ids'].append(c['claim_id'])
for name,rows in [('SOURCES',sources.values()),('CLAIMS',claims)]:
    (ROOT/(name+'.jsonl')).write_text(''.join(json.dumps(x,ensure_ascii=False)+'\n' for x in rows),encoding='utf-8')
summary=dict(source_records=len(sources),seed_records=28,added_document_records=29,data_series_records=10,failed_data_candidates=1,read_depth_counts=dict(collections.Counter(x['read_depth'] for x in sources.values())),source_families=len(set(x['source_family_id'] for x in sources.values())),reviewed_research_families=sorted(set(x['source_family_id'] for x in sources.values() if x['reviewed_research_family'])),claim_count=len(claims),assessment_counts=dict(collections.Counter(x['assessment'] for x in claims)),decision_delta_counts=dict(collections.Counter(x['decision_delta'] for x in claims)))
(ROOT/'data/derived/REGISTER_SUMMARY.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2),encoding='utf-8')
assert len(claims)==32 and all(c['assessment']!='UNASSESSED' for c in claims)
print(json.dumps(summary,ensure_ascii=False,indent=2))
